import { Iproduct, ProductStatus } from "./i-product";


export const productsList: Iproduct[] = [
    {
      id: 1,
      productName:'شنطة سفر متميزة',
      price: 3000,
      quantity: 50,
      productStatus: ProductStatus.AlmostFinish, // Placeholder value; change according to your needs
      Ranking: "قص الشعر",
      tax: 15 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 2,
      productName:'شنطة سفر متميزة',
      price: 8000,
      quantity: 100,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز لابتوب",
      tax: 13 ,
      minNumber: 50,
      discount: 50,
      SellingRate: false,
    },
    {
      id: 3,
      productName:'شنطة سفر متميزة',
      price: 5000,
      quantity: 200,
      productStatus: ProductStatus.Unavailable,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 4,
      productName:'شنطة سفر متميزة',
      price: 8000,
      quantity: 30,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز لابتوب",
      tax: 14 ,
      minNumber: 50,
      discount: 105,
      SellingRate: false,
    },
    {
      id: 5,
      productName:'شنطة سفر متميزة',
      price: 4000,
      quantity: 50,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
    {
      id: 6,
      productName:'شنطة سفر متميزة',
      price: 5000,
      quantity: 200,
      productStatus: ProductStatus.Unavailable,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 7,
      productName:'شنطة سفر متميزة',
      price: 8000,
      quantity: 30,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز لابتوب",
      tax: 14 ,
      minNumber: 50,
      discount: 105,
      SellingRate: false,
    },
    {
      id: 8,
      productName:'شنطة سفر متميزة',
      price: 4000,
      quantity: 50,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
    {
      id: 9,
      productName:'شنطة سفر متميزة',
      price: 5000,
      quantity: 200,
      productStatus: ProductStatus.Unavailable,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 10,
      productName:'شنطة سفر متميزة',
      price: 8000,
      quantity: 30,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز لابتوب",
      tax: 14 ,
      minNumber: 50,
      discount: 105,
      SellingRate: false,
    },
    {
      id: 11,
      productName:'شنطة سفر متميزة',
      price: 4000,
      quantity: 50,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
    {
      id: 12,
      productName:'شنطة سفر متميزة',
      price: 5000,
      quantity: 200,
      productStatus: ProductStatus.Unavailable,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 13,
      productName:'شنطة سفر متميزة',
      price: 8000,
      quantity: 30,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز لابتوب",
      tax: 14 ,
      minNumber: 50,
      discount: 105,
      SellingRate: false,
    },
    {
      id: 14,
      productName:'شنطة سفر متميزة',
      price: 4000,
      quantity: 50,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
  ];