import { Iproduct, ProductStatus } from "./i-product";


export const productsList: Iproduct[] = [
    {
      id: 1,
      productName:'شنطة سفر متميزة',
      price: 3000,
      quantity: 50,
      productStatus: ProductStatus.AlmostFinish, // Placeholder value; change according to your needs
      Ranking: "قص الشعر",
      tax: 15 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 2,
      productName:'شنطة سفر متميزة',
      price: 800,
      quantity: 100,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز لابتوب",
      tax: 13 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
    {
      id: 3,
      productName:'شنطة سفر متميزة',
      price: 50,
      quantity: 200,
      productStatus: ProductStatus.Available,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 4,
      productName:'شنطة سفر متميزة',
      price: 80,
      quantity: 30,
      productStatus: ProductStatus.Unavailable,
      Ranking: "جهاز لابتوب",
      tax: 14 ,
      minNumber: 50,
      discount: 105,
      SellingRate: true,
    },
    {
      id: 5,
      productName:'شنطة سفر متميزة',
      price: 40,
      quantity: 50,
      productStatus: ProductStatus.Unavailable,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
    {
      id: 6,
      productName:'شنطة سفر متميزة',
      price: 30,
      quantity: 20,
      productStatus: ProductStatus.Unavailable,
      Ranking: "قص الشعر",
      tax: 12 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 7,
      productName:'شنطة سفر متميزة',
      price: 120,
      quantity: 10,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز لابتوب",
      tax: 15 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 8,
      productName:'شنطة سفر متميزة',
      price: 100,
      quantity: 15,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "قص الشعر",
      tax: 14 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
    {
      id: 9,
      productName:'شنطة سفر متميزة',
      price: 70,
      quantity: 25,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز لابتوب",
      tax: 13 ,
      minNumber: 50,
      discount: 100,
      SellingRate: true,
    },
    {
      id: 10,
      productName:'شنطة سفر متميزة',
      price: 50,
      quantity: 40,
      productStatus: ProductStatus.AlmostFinish,
      Ranking: "جهاز موبيل",
      tax: 12 ,
      minNumber: 50,
      discount: 50,
      SellingRate: true,
    },
  ];